version: "2"
services:
  influxdb:
    networks:
      - server_client
    image: influxdb:2.0
    ports:
      - "8086:8086"
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=traffic-bucket
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=distribuidos
      - DOCKER_INFLUXDB_INIT_ORG=unlp
  
  grafana:
    networks:
      - server_client
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    links:
      - influxdb
    restart: always

networks:
  server_client:
