# Use an official Maven image as the base image
FROM maven:3.8.4-openjdk-11-slim
# Set the working directory in the container
RUN apt-get update && apt-get install -y make

WORKDIR /opt/app/

EXPOSE 8080

ENV SOCKET_ENV=frontend

CMD ["make", "server"]
